//
//  Categories.swift
//  BetterKnow
//
//  Created by Denielle Abaquita on 10/9/21.
//

import UIKit

class Category {
    var title: String = ""
    var image: UIImage
    var topics: [Topic]
    
    init(title: String, image: UIImage, topics: [Topic]) {
        self.title = title
        self.image = image
        self.topics = topics
    }
    
    // Implement this and return our categories holding various topics
    static func FetchCategories() -> [Category] {
        return [
           Category(
            title: "General Information",
            image: UIImage(systemName: "book")!,
            topics: [Topic(title: "How can I tell if health information is good or bad?", description: "     Anyone can post anything online. It's up to the readers to think critically about information to decide if it seems helpful, truthful, or safe. Here are key points to keep in mind as you determine which information is worth considering and which information doesn't pass the test.\n     It's so easy to spread information online, and we can't assume that the source we're reading or watching is the original source. Before you can evaluate anything, you need to know where the claims come from and determine if it's a reliable source.\n     Reliable sources on the coronavirus and COVID-19 illness include the World Health Organization (WHO), Government of Canada ministries and agencies like Health Canada and the Public Health Agency of Canada, the Government of BC ministries and agencies like the BC Ministry of Health, and the BC Centre for Disease Control (BCCDC). Scientists and researchers at universities and other institutions and health sciences professionals are also important sources of information.\n     Read the entire story or post before you make any decisions\nHeadlines and titles need to be simple and short, so they can sometimes be misleading on their own. They may also be purposefully shocking or controversial to entice you to click to read more\n     Look at the author\n Websites that belong to governments, government-funded agencies, well-known health providers, universities, or groups of medical professionals are generally the most reliable. Be careful of sites that don't list the author or don't tell you much about themselves. Double-check the author and the credentials of any 'experts' quoted or cited to see if they are actually experts in the topic being discussed.\n     See what other sources say\n Can you find other evidence from other sources to support the claims? Does the author list their sources? Are the sources legitimate, like research journals?"),
                     Topic(title: "How can I take care of my physical health?", description: "Eat well\n     Try to eat as well as you can. It may be easier to reach for unhealthier comfort foods and snacks while you spend more time at home, but try to keep a balanced approach. When you stock up on groceries, don’t ignore fresh fruit and vegetables—we still have everything we need to prepare food. Now that we're advised to limit the amount of time we spend in public spaces like grocery stores, this is a great time to try out new fruits and vegetables that keep at home for longer periods of time.\n     If it's safer for you to stay home or you are in self-isolation, reach out for help. Many grocery stores and meal prep services offer safe, no-contact delivery. You can also ask family or friends to bring you groceries, or look for local COVID-19 support groups on social media. It's safest if others leave food and other supplies outside of your door to avoid spreading the virus.\nStay active\n     Exercise is an important part of mental health and well-being, stress management, and health sleep. However, it's something that many people give up when they start to feel stressed or overwhelmed. If it's safe for you to do so, spend time outside. You should still avoid busy areas or groups and stay at least two metres away from others, but there is no reason to avoid walks, runs, or other safe outdoor activities. (Note that some municipalities, BC Parks, and Parks Canada have restricted some outdoor spaces to reduce crowds, so check the status of your local parks or trails and respect closures—they're just keeping everyone safe.)\n     If you prefer to exercise indoors, you can also find many different exercises classes online. You can try yoga, follow a barre class, work on your cardio, pick up a new dumbbell routine, and keep up with Crossfit WODs from the comfort of your living room. Look for no-equipment exercise routines or classes if you don't already have equipment.\n     Poor sleep can make even simple problems feel a lot worse than they really are. Poor sleep can affect your mood, your outlook, and your patience. Unfortunately, stress and anxiety can really take a toll on your sleep. If you're having a hard time sleeping, be proactive and practice healthy sleep habits.\n     If you have other health problems like a chronic illness, check in with your doctor or health care team to see if you need to take any additional measures or precautions. Remember to plan ahead and do what you can to keep prescription or over-the-counter medications, medical supplies, supplements, or other health needs on hand."),
                     Topic(title: "How can I use distractions to manage difficult thoughts or feelings?", description: "Distraction is a very valid tool to help you cope when everything feels overwhelming or when you feel lonely or isolated.If you don't have a lot of energy or focus right now, try low-effort distractions like watching TV, browsing Youtube, listening to a podcast or audiobook, playing a game on your phone, reading an easy book or magazine, or working on a simple art project.If you have more energy and focus, give yourself a to-do list every day: you can clean and take care of projects around your home, work on hobbies, connect with family or friends, read a new book and catch up on your favourite TV shows. You can find interesting opportunities to take online courses from universities all over the world through MOOCs and other online learning platforms, you can learn a new language online or through apps, and you can learn new hobbies and activities. As more people have to practice social distancing or self-isolation, people are finding creative ways to bring the world into their homes: you can tour museums and art galleries, Skype with a scientist, watch animals at zoos and nature preserves, and more.\n     When normal schedules are disrupted, it's easy to fall into unhelpful habits. Look for ways to keep yourself on track with healthier habits. You could set yourself goals every day or turn activities into a fun competition with friends or family—whoever takes the most language classes wins!\n     Many communities are using social media platforms like Facebook to organize support and help for neighbours. If you are healthy and it's safe to do so, you can sign up to walk dogs, pick up groceries and household supplies, and help others who can't go out at the moment. This can be a great way to make new connections in your area, and helping others is good for your own mental health. Just be sure to follow good hygiene practices and physical distancing—your own health is important."),
                     Topic(title: "How can I maintain social connections? What if I fell lonely?", description: "A lot of people are alone right now, but we don't have to be lonely. We're all in this together.\n     While you may be physically separated from friends, family members, and other loved ones, it has never been more important to maintain those social connections. Social connections are an opportunity to seek and share support, talk through difficult feelings, share a laugh, keep up-to-date with loved ones, and help each other cope. This pandemic is a lot for one person to deal with on their own. While measures like physical distancing and self-isolation are necessary to slow the spread of the virus, the physical separation can amplify a lot of challenging emotions like loneliness and fear.\n     Think about the different ways to connect that are most meaningful for you. For example, you might prefer a video chat over a phone call, or you might prefer to text throughout the day rather than one set time for a video call. Then, work with your social networks to make a plan. You might video chat with your close friends in the evening and phone a family member once a week.\n     Remember to be mindful of people who may not be online. Check in by phone and ask how you can help.\n     The quality of your social connections matter. Mindlessly scrolling through social media and liking a few posts usually doesn't build strong social connections. Make sure you focus on strategies that actually make you feel included and connected. If your current strategies don't help you feel connected, problem-solve to see if you can find a solution.\n     Everyone feels lonely at times—maybe you recently moved to a new city, are changing your circle of friends, lost someone important in your life, or lost your job and also lost important social connections with coworkers. Other people may have physical connections to others but may feel like their emotional or social needs aren't met. Measures like social distancing or self-isolation can make loneliness feel worse no matter why you feel lonely now."),
                     Topic(title: "How can I manage grief?", description: "Grief bring up complicated feelings. You might feel sad, angry, frustrated, fearful, or hopeless. You may have a hard time eating or sleeping, or feel very tense. You may feel overwhelmed and tired. You may wonder if life will ever feel normal again.\nEveryone grieves in their own way and their own time. Here are some strategies to try as you navigate your own journey.\nAcknowledge and express your feelings in a healthy way. Give your feelings a name and find healthy ways to express them, such as by talking with a friend, writing in a journal, or making art.\nGive yourself as much time as you need. Grief follows its own schedule. Give yourself permission to use this time to take care of your well-being. Let go of expectations, tasks, or other obligations that can wait.\nSeek support. Grief can feel very isolating, even though a lot of people are experiencing some sort of loss right now. Reach out to friends or family and share your feelings. Look for ways to help and support each other.\nTake care of yourself. Ignoring health and well-being can make difficult experiences feel worse. Eat as well as you can, try to get enough sleep, spend time outside if it's safe for you to do so, and exercise regularly. Think about self-care activities or strategies that have helped you cope with challenging situations in the past and make time for those activities.\nKnow that feelings of grief will pass. Grief may feel intense at times, but those feelings will become more manageable over time and will eventually pass.\nConnect with a mental health professional if you're having a hard time. If you're having a hard time getting through the day, coping in unhealthy ways, or having a hard time managing difficult thoughts or feelings, it's a good idea to seek help from a professional like a psychologist or counsellor—many now offer online or phone appointments."),
                     Topic(title: "How can I reframe the situation and find more balanced perspectives?", description: "How you think about something impacts your feelings and your behaviours.\nWhen we feel stressed out, angry, or fearful, it's hard to look at the situation realistically and see all of the options we have. (Remember: we all control our own actions and reactions, no matter what's going on in the world. We can call do something about this pandemic.)\nPeople often overestimate the negative parts—their own feelings, their own abilities to manage a difficult situation, or the situation itself—and underestimate positive parts—their own abilities to care for themselves and loved ones, their support networks, and opportunities.\nHow does the thought We're never going to make it through this! make you feel? It likely does not feel good—and it is not even true. \nChallenging negative, unhelpful thoughts can improve your mood, validate your ability to get through this, and help you see new options or opportunities to stay well.\nStop and notice thoughts that come up. How do they make you feel? Do your thoughts seem realistic if you look at the situation more objectively? How can you reframe the thought to make it more productive or hopeful? Can you find any positive aspects or think of new ways to approach the situation?"),]
           ),
           Category(
            title: "Finding Help",
            image: UIImage(systemName: "book.fill")!,
            topics: [Topic(title: "How can I see a counsellor?", description: "You can make an appointment on your own. You don’t need a doctor’s referral to see a counsellor.\nCounsellors are not usually covered by MSP, so you’ll have to pay for the cost of the appointment yourself. Workplace extended health benefits, Employee (Family) Assistance Programs, or private health insurance plans may help cover some costs. Some counsellors may offer a sliding scale based on your income. If you’re facing financial hardship, you can ask when you make the appointment.\nIf you see a counsellor through a public mental health centre like a mental health team or outpatient psychiatry program, it will still be covered by MSP. Talk to your care provider if you have questions or want to learn more."),
                     Topic(title: "How can I find a support group?", description: "Support groups are a way for people with a common experience to help each other and learn from each other. There are support groups for people with any experience of mental illness, support groups for people with a specific diagnosis, support groups for family members and friends, and more.\nSupport groups are offered by community organizations, mental health service providers, schools, campuses, and support agencies.\nIn order to benefit the most from a support group, you need to feel safe enough to share your experiences and thoughts, and you need to feel comfortable supporting others. It can be helpful to contact the group facilitator or organizer ahead of time to see if a particular group might be a good fit for you.\nSometimes a group just doesn’t work for you, and that’s okay. If you feel comfortable, you can try talking to the facilitator to see if they can recommend another group that you can try."),
                     Topic(title: "Where can I find child and youth mental health services?", description: "To find help for a child or youth, you can:\nEncourage your child to talk to a teacher or school counsellor\nTalk to your family doctor or pediatrician, or go to a walk-in clinic\nContact your local Child & Youth Mental Health office on one of their walk-in days\nUse Kelty Mental Health’s Help Finder Tool to find specific services and providers\nContact the Institute of Families for Child and Youth Mental Health’s Youth-in-Residence or Parent-in-Residence for guidance, information, and support. Youth-in-Residence and Parents-in-Residence are located around the province. If you don’t have one in your community, a Parent- or Youth-in-Residence at the Kelty Mental Health Resource Centre can help you by phone or email\nVisit www.familysmart.ca for information and resources on child and youth mental health\nFor young people ages 12-24, visit foundrybc.ca to see if there is a Foundry Centre in your area. Foundry offers easy-to-access mental health care, physical health care, social services, and support out of one office."),
                     Topic(title: "Where can older adults find help for mental health concerns?", description: "Mental health concerns are a serious concern at any age, and everyone deserves help and support. If you’re concerned about your mental health, you can:\nTalk to your family doctor or go to a walk-in clinic\nCall the Mental Health Support Line at 310-6789 (no area code) for information about services in your area\nFind your local mental health centre or program at www.gov.bc.ca/mentalhealth (you may need a doctor’s referral to access some programs)\nFind your local Canadian Mental Health Association branch at www.cmha.bc.ca and ask for information about local services\nContact a local senior’s support organization or group and ask for advice. You can search for organizations at www.bc211.ca\nFor general information about senior’s mental health:\nFind resources from the Canadian Coalition for Seniors' Mental Health at www.ccsmh.ca\nFind info sheets in the Seniors and Depression Series at www.heretohelp.bc.ca/factsheet/seniors-and-depression-series"),
                     Topic(title: "Where can I find self-help materials for anxiety?", description: "Self-help resources are not a substitute for diagnosis or treatment. If you have concerns about low mood, it’s best to talk to your doctor first and rule out physical causes for your symptoms. However, once you’ve checked in with your doctor, self-help materials can be a great way to learn more about anxiety and practice different skills at your own pace or in between treatment sessions. Here are some resources to check out:\nAnxiety Canada has self-help resources, toolkits, worksheets, and videos on anxiety and anxiety disorders for children and their parents, teens, adults, expecting and new moms at www.anxietycanada.com. Their MindShift app teaches skills to help users manage anxiety, relax, and live well. Although designed for teens and young adults, other adults can also benefit from it.\nThere are many books and workbooks available to help people who experience anxiety problems. Talk to your mental health. Talk to your mental health care team for recommendations. There are bookstores that specialize in mental health and well-being materials, such as Odin Books in Vancouver. Within British Columbia, you may also borrow books for free from the Family Support and Resource Centre at BC Children’s and Women’s Hospitals. They have many self-help and reference materials on depression for women and their partners, for parents, and for children and youth.\nIf you’d like self-help materials with a bit of extra support from a person, Bounce Back: Reclaim Your Health is a guided self-help program for British Columbians who experience mild to moderate low mood or anxiety. You can get a DVD of tips to help you recognize and manage symptoms of anxiety, or you can learn more in-depth skills in a series of workbooks you complete at home. You work with a trained coach from the Canadian Mental Health Association who will offer support and advice by telephone or video conference. Bounce Back is free with a doctor’s referral. For more information, visit www.bouncebackbc.ca. If you want to access the Bounce Back materials without a coach or referral, you can do that online in BC at www.bouncebackonline.ca."),
                     Topic(title: "Where can I find self-help materials for depression?", description: "Self-help resources are not a substitute for diagnosis or treatment. If you have concerns about low mood, it’s best to talk to your doctor first and rule out physical causes for your symptoms. However, once you’ve checked in with your doctor, self-help materials can be a great way to learn more about depression and practice different skills at your own pace or in between treatment sessions. Here are some resources to check out.\nOften depression can affect your concentration and motivation to work through self-help materials on your own. If you’d like self-help materials with a bit of extra support from a person, Bounce Back: Reclaim Your Health is a guided self-help program for British Columbians who experience mild to moderate depression, low mood, stress, or anxiety. You can get a DVD of tips to help you recognize and manage symptoms of depression, or you can learn more in-depth skills in a series of workbooks you complete at home. You also work with a trained coach from the Canadian Mental Health Association who will offer support and advice by telephone or video conference. Bounce Back is free with a doctor’s referral. For more information, visit www.bouncebackbc.ca (If you want to access the Bounce Back materials without a coach or referral, you can do that online in BC at www.bouncebackonline.ca)."),
                     Topic(title: "An adult in may life seems ill and won’t find help. What can I do?", description: "There are two important points to think about. First, diagnosing a health condition, especially when symptom-checking is so easy online, can be dangerous. Diagnosis is still always best left to professionals who can look at the whole picture. Remember, too, that the person you care about may have a very different idea of what’s causing their difficulties and what the negative impacts are on their life. Second, except in rare cases, the person being treated needs to be an active player in their own recovery to continue with their treatment, just as they would for any other health problem. If the vast majority of cases, you cannot do this work entirely for them—and trying to do so may damage your relationship.It’s difficult when an adult child, sibling, parent, friend, co-worker, or other important person is struggling or behaving in ways that are causing harm. This can be a tricky situation—you want to help, but most adults are responsible for their own care.\nBe honest about your concerns, the impacts you are seeing that worry you, listen to their point of view and work together to find a solution that works for everyone, even if it means a compromise. You may want to offer to go with them to an appointment, encourage them to do an online screening self-test, or involve someone else close to them who may be similarly concerned and may have more influence in encouraging them to notice changes and seek help. Because you may be feeling frustrated and helpless, it’s important to get care and support for yourself during this time, especially if you’re very close to the person you’re worried about."),
                     Topic(title: "I’m worried about my child or teenager. Where can I find help? ", description: "Child & Youth Mental Health teams from the Ministry of Children and Family Development can assess and treat mental health problems in young people ages 18 and under as well as refer families to additional services in your area.\nIf your child’s difficulties affect their performance or behaviour at school, the school may be involved. If your child’s school has a counsellor, talk to them about services you can access through the school. School counsellors can also suggest community services.\n"),
                     Topic(title: "I’m a young person and one of my parents has mental illness. What can I do?", description: "Someone else’s illness is not your fault. You also can’t control how someone else feels, their illness, or the things they do or say. What you can do is take care of yourself.\nIt’s important to take care of yourself, too! A lot of people have a big mix of feelings when a parent isn’t well. You might feel angry, embarrassed, scared, or many other things. These feelings and experiences can have a big impact on the way your think about yourself and other people. When you’re on an airplane and the flight attendants go through the safety demonstration, they tell you to put your own oxygen mask on before your help other people. That’s because it’s hard to help someone else if you aren’t well yourself.")]
           ),
           Category(
            title: "Support",
            image: UIImage(systemName: "book.closed")!,
            topics: [Topic(title: "How can I pay for mental health care?", description: "Mental health services provided through the government-run (‘public’) system, like services you receive through your local mental health centre or team, an outpatient psychiatry at a hospital are most often completely covered by MSP. As long as you are eligible for MSP, you won’t have to pay to see someone.\nFor mental health services that aren’t covered by MSP, such as psychotherapy or counselling with a private practitioner, you will have to cover the costs yourself.\nIf costs are a barrier to health care, talk to your doctor to see if there are any services in the public health system (covered by MSP) that may be a good fit for you. You can also called the Mental Health Support Line at 310-6789 (no area code) for more information on local mental health services."),
                     Topic(title: "Can I get help paying for prescription medications? ", description: "BC PharmaCare covers the cost of some medications through Plan G, the Psychiatric Medications Plan, for people who need a medication to be well but cannot afford them. Your doctor or nurse practitioner must apply for your coverage on your behalf. Coverage usually lasts for one year, and then you can reapply if needed. Talk to your care team if you’re interested in Plan G.")]
           ),
           Category(
            title: "Understanding systems and treatments",
            image: UIImage(systemName: "pills")!,
            topics: [Topic(title: "What’s the difference between psychotherapy and counseling?", description: "Psychotherapy and counselling have a lot in common and usually mean the same thing. Both are used to describe professionals who use talk-based approaches to help someone recover from a mental illness or mental health problem. Many different professionals may provide counselling or psychotherapy, including registered psychologists, registered clinical counsellors, psychiatrists, other therapists and counsellors, family doctors, psychiatric nurses, and faith leaders.\nIt’s useful to talk to someone about any problem—a lot of people find that simply talking with friends or family can help them feel better. A professional therapist or counsellor can offer more: they have training, experience, and emotional distance (since they don’t know you). They use different theories to listen to you, support you, and approach different problems or patterns. For example, a psychotherapy called cognitive-behavioural therapy is based on the theory that learning skills to change your thinking and actions can positively impact your emotions, well-being, and future thoughts and behaviours. A therapist could help you learn and practice these skills.\nThere are many psychotherapies with good evidence of being effective for different problems or illnesses. A few examples include cognitive-behavioural therapy, interpersonal therapy, dialectical behaviour therapy, solutions-focused brief psychotherapy, narrative therapy, and emotion-focused therapy.\nIn general, some aspects of therapy and counselling are the same, no matter which approach you choose: the expectations you bring to your counselling sessions, the match between your understanding of the problems and your therapist’s understanding of the problem, and the trust and rapport that you have with your therapist. In fact, one research review found that 50% of the improvement seen in clients who just received active listening and support from a counsellor (called non-directive supportive therapy) was due simply to the relationship between client and therapist.1 Psychotherapy can and does work, but the professional you choose, and their match with your values, is also very important."),
                     Topic(title: "I received a diagnosis but I don’t think it’s right. What can I do?", description: "If possible, bring up your concerns with the professional who provided the diagnosis. That way, the professional can answer your questions and you can better understand their decision.\nIf that doesn’t resolve the situation or a follow-up appointment isn’t possible, you can ask for a second opinion. A second opinion is an assessment from a different professional. This can give you better understanding of what’s going on and what to do about it. Second opinions are common when it comes to major health decisions—you won’t hurt anyone’s feelings and your doctor will try to accommodate reasonable requests for a second opinion. Talk to your family doctor (or go to a walk-in clinic) to discuss your options and get a referral to a different program or health professional, if needed."),
                     Topic(title: "I was prescribed an antidepressant but I don’t think it’s working. What can I do?", description: "If you’re concerned about your medications, it’s important to talk with the doctor or psychiatrist who prescribed your medications. While it can take a few weeks to really see improvements with many antidepressants, it’s still a good idea to talk to your doctor about what to expect.\nTalk to the doctor that prescribed your medication if you experience symptoms or side effects that are distressing you. If you want to talk to a trusted professional about the most common side effects, call your pharmacist. You can reach a pharmacist by phone after-hours by calling 811.\nIt’s also best not to stop taking the medication or changing the dose on your own without first talking to a health care provider. While it might be tempting to stop taking your medication when you start feel better, it’s important to follow your doctor’s instructions.\nIn some cases, people can have an allergic reaction to a medication. Some reactions are not serious, like a rash. In these cases, you can call the pharmacist or call 811 to reach help after-hours. If you have a serious reaction like difficult breathing, dizziness, or confusion, call 911 right away.\nWhen you start a new medication, your pharmacist will give you a printout with information like side effects, signs of an allergic reaction, how long it might take to work, and other information. It’s good information to keep on hand, but it isn’t always easy to read. When you pick up your medication, you can ask the pharmacist to go over the information with you so you understand what you should look for.\nIf a particular antidepressant or psychiatric medication just isn’t working for you, there are many different options! Unfortunately, finding the right medication can take some trial and error. Different people can have very different experiences with the same medication, and often you need to try something to see if it works (or doesn’t work) for you. This can be a frustrating process, especially when you want to start feeling better, but it’s important to keep trying and work with your doctor so you understand your options. Many people feel intimidated talking to health professionals, but it’s important to share information so you both understand what’s going on and can make good, informed decisions about your health care. Some people also feel embarrassed talking about symptoms or side effects like changes in sex drive or digestion, but its important information for your doctor (and they know that changes in sex drive or digestion are common concerns).")]
           )
        ]
    }
}
